JackWilkinson_P4063103-2/JackWilkinson_P4063103-1/JackWilkinson_P4063103/ConsoleApplication1/ICATask1/Controllers/BusinessUnitController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HebbraCo_Lib;

namespace ICATask1.Controllers
{
    public class BusinessUnitController : Controller
    {
        private HebbraCo_Lib.HebbCo_Model db = new HebbraCo_Lib.HebbCo_Model();

        // GET: BusinessUnit
        public ActionResult Index()
        {
            var bu = db.BusinessUnits.Where(b => b.Active == true);
            return View(bu);
        }

        // GET: BusinessUnit/Details/5
        public ActionResult Details(int id)
        {
            BusinessUnit bu = db.BusinessUnits.Find(id);

            if (bu == null || bu.Active == false)
            {
                return HttpNotFound();
            }

            return View(bu);
        }

        // GET: BusinessUnit/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BusinessUnit/Create
        [HttpPost]
        public ActionResult Create(BusinessUnit bu)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.BusinessUnits.Add(bu);
                    bu.Active = true;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View(bu);
            }
        }

        // GET: BusinessUnit/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            BusinessUnit bu = db.BusinessUnits.Find(id);

            if (bu == null || bu.Active == false)
            {
                return HttpNotFound();
            }

            return View(bu);
        }

        // POST: BusinessUnit/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, BusinessUnit bu)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(bu).State = EntityState.Modified;
                    bu.Active = true;
                    db.SaveChanges();  
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View(bu);
            }
        }

        // GET: BusinessUnit/Delete/5
        public ActionResult Delete(int id)
        {
            BusinessUnit bu = db.BusinessUnits.Find(id);
            int staffCount = bu.Staffs.Where(s => s.Active == true).Count();
            if (staffCount > 0)
            {
                return RedirectToAction("Index");
            }
            if (bu == null || bu.Active == false)
            {
                return HttpNotFound();

            }
            return View(bu);
        }

        // POST: BusinessUnit/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, BusinessUnit bu)
        {
            try
            {
                bu = db.BusinessUnits.Find(id);
                if (bu.Active == true)
                {
                    bu.Active = false;
                }
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

JackWilkinson_P4063103-2/JackWilkinson_P4063103-1/JackWilkinson_P4063103/ConsoleApplication1/ICATask1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ICATask1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

JackWilkinson_P4063103-2/JackWilkinson_P4063103-1/JackWilkinson_P4063103/ConsoleApplication1/ICATask1/Controllers/StaffController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HebbraCo_Lib;

namespace ICATask1.Controllers
{
    public class StaffController : Controller
    {
        private HebbCo_Model db = new HebbCo_Model();

        // GET: Staff
        public ActionResult Index()
        {
            var staff = db.Staffs.Where(s => s.Active == true);
            return View(staff);
        }

        // GET: Staff/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = db.Staffs.Find(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            return View(staff);
        }

        // GET: Staff/Create
        public ActionResult Create()
        {
            var items = db.BusinessUnits.Where(bu => bu.Active == true);
            ViewBag.businessUnitID = new SelectList(items, "businessUnitID", "title");
            return View();
        }

        // POST: Staff/Create
        [HttpPost]
        public ActionResult Create(Staff st)
        {
            try
            {

                if (ModelState.IsValid)
                {
                    db.Staffs.Add(st);
                    st.Active = true;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View(st);
            }
        }

        // GET: Staff/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            Staff staff = db.Staffs.Find(id);
            if (staff == null || staff.Active == false)
            {
                return HttpNotFound();
            }
            ViewBag.businessUnitId = new SelectList(db.BusinessUnits, "businessUnitId", "businessUnitCode",
                staff.businessUnitId);
            return View(staff);
        }

        // POST: Staff/Edit/5
        [HttpPost]
        public ActionResult Edit(
            [Bind(
                Include =
                    "staffId,businessUnitId,staffCode,firstName,middleName,lastName,dob,startDate,profile,emailAddress,Active"
                )] Staff staff)
        {
            try
            {

                if (ModelState.IsValid)
                {
                    db.Entry(staff).State = EntityState.Modified;
                    staff.Active = true;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return RedirectToAction("Index");
            }
            catch
            {
                ViewBag.businessUnitId = new SelectList(db.BusinessUnits, "businessUnitId", "businessUnitCode",
                    staff.businessUnitId);
                return View(staff);
            }
        }

        // GET: Staff/Delete/5
        public ActionResult Delete(int id)
        {
            Staff staff = db.Staffs.Find(id);
            if (staff == null || staff.Active == false)
            {
                return HttpNotFound();
            }
            return View(staff);
        }

        // POST: Staff/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult Delete(int id, Staff staff)
        {
            try
            {
                staff = db.Staffs.Find(id);
                if (staff.Active == true)
                {
                    staff.Active = false;
                }
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult StaffBBU(int id)
        {
            var staffsBbu = db.Staffs.Where(s => s.Active == true).Where(s => s.businessUnitId == id);
            int sCount = staffsBbu.Count();
            if (sCount < 0)
            {
                return View("Index");
            }
            return View(staffsBbu);
        }
            
        }

}

JackWilkinson_P4063103-2/JackWilkinson_P4063103-1/JackWilkinson_P4063103/ConsoleApplication1/ICATask1/Views/BusinessUnit/Create.cshtml
@model HebbraCo_Lib.BusinessUnit

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BusinessUnit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.businessUnitCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.businessUnitCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.businessUnitCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.officeAddress1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.officeAddress1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.officeAddress1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.officeAdresss2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.officeAdresss2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.officeAdresss2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.officeAddress3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.officeAddress3, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.officeAddress3, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.officePostCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.officePostCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.officePostCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.officeContact, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.officeContact, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.officeContact, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.officePhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.officePhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.officePhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.officeEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.officeEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.officeEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

JackWilkinson_P4063103-2/JackWilkinson_P4063103-1/JackWilkinson_P4063103/ConsoleApplication1/ICATask1/Views/BusinessUnit/Delete.cshtml
@model HebbraCo_Lib.BusinessUnit

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BusinessUnit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.businessUnitCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.businessUnitCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.officeAddress1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.officeAddress1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.officeAdresss2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.officeAdresss2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.officeAddress3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.officeAddress3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.officePostCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.officePostCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.officeContact)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.officeContact)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.officePhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.officePhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.officeEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.officeEmail)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

JackWilkinson_P4063103-2/JackWilkinson_P4063103-1/JackWilkinson_P4063103/ConsoleApplication1/ICATask1/Views/BusinessUnit/Details.cshtml
@model HebbraCo_Lib.BusinessUnit

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>BusinessUnit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.businessUnitCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.businessUnitCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.officeAddress1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.officeAddress1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.officeAdresss2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.officeAdresss2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.officeAddress3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.officeAddress3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.officePostCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.officePostCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.officeContact)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.officeContact)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.officePhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.officePhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.officeEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.officeEmail)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.businessUnitId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

JackWilkinson_P4063103-2/JackWilkinson_P4063103-1/JackWilkinson_P4063103/ConsoleApplication1/ICATask1/Views/BusinessUnit/Edit.cshtml
@model HebbraCo_Lib.BusinessUnit

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BusinessUnit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.businessUnitId)

        <div class="form-group">
            @Html.LabelFor(model => model.businessUnitCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.businessUnitCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.businessUnitCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.officeAddress1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.officeAddress1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.officeAddress1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.officeAdresss2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.officeAdresss2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.officeAdresss2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.officeAddress3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.officeAddress3, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.officeAddress3, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.officePostCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.officePostCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.officePostCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.officeContact, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.officeContact, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.officeContact, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.officePhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.officePhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.officePhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.officeEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.officeEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.officeEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

JackWilkinson_P4063103-2/JackWilkinson_P4063103-1/JackWilkinson_P4063103/ConsoleApplication1/ICATask1/Views/BusinessUnit/Index.cshtml
@model IEnumerable<HebbraCo_Lib.BusinessUnit>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.businessUnitCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
       
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.businessUnitCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.description)
        </td>
        
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.businessUnitId }) |
            @Html.ActionLink("Details", "Details", new { id=item.businessUnitId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.businessUnitId }) |
            @Html.ActionLink("Staff", "StaffBBU", "Staff", new { id = item.businessUnitId }, null)
        </td>
    </tr>
}

</table>

JackWilkinson_P4063103-2/JackWilkinson_P4063103-1/JackWilkinson_P4063103/ConsoleApplication1/ICATask1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

JackWilkinson_P4063103-2/JackWilkinson_P4063103-1/JackWilkinson_P4063103/ConsoleApplication1/ICATask1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

JackWilkinson_P4063103-2/JackWilkinson_P4063103-1/JackWilkinson_P4063103/ConsoleApplication1/ICATask1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

JackWilkinson_P4063103-2/JackWilkinson_P4063103-1/JackWilkinson_P4063103/ConsoleApplication1/ICATask1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Staff", "Index", "Staff")</li>
                    <li>@Html.ActionLink("Business Units", "Index", "BusinessUnit")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>