JackWilkinson_P4063103-2/JackWilkinson_P4063103-1/JackWilkinson_P4063103/ConsoleApplication1/ICATask4/Controllers/SkillsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ICATask4.Models;
using HebbraCo_Lib;
using ICATask4.SkillService;

namespace ICATask4.Controllers
{
    public class SkillsController : Controller
    {
        //this will instantiate the model for the skills database
        private SkillService.SkillServiceClient WCFClient = new SkillService.SkillServiceClient();
        //this will instantiate the model for the WCF Client
        private HebbraCo_Lib.task4Model skilldb = new task4Model();


        public ActionResult WcfResult()
        {
            //this method will retreive all of the skills from the WCF client
            //and will return the skills in a formatted list
            var skills = WCFClient.GetAllSkills();
            return View(skills);

        }

        public ActionResult Skills(string staffCode)
        {
            //this method will allow display all skills of a certain staff member using the staff code
            var thisStaffSkills = skilldb.skillStaffs.Where(s => s.staffName == staffCode);
            var vm = thisStaffSkills.Select(
                c => new skillDTO
                {
                    skillCode = c.skillCode,
                    staffName = c.staffName
                });
            return View(vm);
        }

    }
}

JackWilkinson_P4063103-2/JackWilkinson_P4063103-1/JackWilkinson_P4063103/ConsoleApplication1/ICATask4/Controllers/StaffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace ICATask4.Controllers
{
    public class StaffController : Controller
    {
        // GET: Staff
        public ActionResult Index(String buCode)
        {
            //this method will connect the web api to all of the staff members and will return 
            //all of the staff members in a formatted view
            HttpClient sClient = new HttpClient();
            sClient.BaseAddress = new System.Uri("http://localhost:33103/");
            sClient.DefaultRequestHeaders.Accept.ParseAdd("application/json");
            HttpResponseMessage response = sClient.GetAsync("api/Staff/StaffBBU/" + buCode).Result;
            if (response.IsSuccessStatusCode)
            {
                var staff = response.Content.ReadAsAsync<IEnumerable<ICATask4.Models.SDTO>>().Result;
                return View(staff);
            }
            return View();
        }

        // GET: Staff/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Staff/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Staff/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Staff/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Staff/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Staff/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Staff/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

JackWilkinson_P4063103-2/JackWilkinson_P4063103-1/JackWilkinson_P4063103/ConsoleApplication1/ICATask4/Views/Staff/Index.cshtml
@model IEnumerable<ICATask4.Models.SDTO>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.staffCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.firstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.middleName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.lastName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model)
{
    <tr>

        <td>
            @Html.DisplayFor(modelItem => item.staffCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.firstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.middleName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.lastName)
        </td>
        <td>
            @Html.ActionLink("View Skills", "Skills","Skills", new { staffCode = item.staffCode }, null)
        </td>
    </tr>

}

</table>